---
- name: Ensure old versions of Docker are not installed
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Ensure additional dependencies are installed (Ubuntu < 20.04)
  apt:
    name: gnupg2
    state: present
  when: ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (Ubuntu >= 20.04)
  apt:
    name: gnupg
    state: present
  when: ansible_distribution_version is version('20.04', '>=')

- name: Add Docker apt key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
